### ISSUE TITLE
Timeout problems cause by `#$ send`

### ISSUE THREAD

**Issue by dashohoxha** [PierreMarchand20/asciinema_automation#18]
I am having timeout problems with a script like this:

```bash
#$ wait 1000                                                                                                                  
#$ delay 5                                                                                                                    

rm -f foo.txt
rm -f .foo.txt.swp

vim foo.txt
#$ sendcharacter i                                                                                                            
#$ send The quick brown fox jumped over the lazy dog.                                                                         
#$ sendcontrol [                                                                                                              
#$ send :wq                                                                                                                   
#$ sendcontrol m                                                                                                              

cat foo.txt
rm -f foo.txt
rm -f .foo.txt.swp
```

The error message:

```
pexpect.exceptions.TIMEOUT: Timeout exceeded.
```

Recording from the script above:  
https://asciinema.org/a/NH9FnPymXYrYW0nZaxjxP4WN2

I don't fully understand why it happens, but I have figured out that if I comment out [this expect line](https://github.com/PierreMarchand20/asciinema_automation/blob/main/asciinema_automation/instruction.py#L68) the problem goes away.

Now I remember that `#$ send password` also didn't work, and I had to send each character of the password one by one with `#$ sendcharacter`, which is inconvenient.

**Comment by PierreMarchand20** [comment]
Using send, it does check that each character is displayed, causing your code to hang. This is done to make the script as robust as possible, in your case, have you tried sendcharacter with multiple characters ? Something like

`
#$ sendcharacter mypassword
`

Should work. Can you try ?

**Comment by dashohoxha** [comment]
Yes, it works, but there is no delay among the characters:

https://asciinema.org/a/9J57VRDHLtspSdC9gGJ0a8rUQ

```bash

#$ wait 1000                                                                                                                  
#$ delay 5                                                                                                                    

rm -f foo.txt
rm -f .foo.txt.swp
vim foo.txt
#$ sendcharacter i                                                                                                            

#$ sendcharacter The quick brown fox jumped over the lazy dog.                                                                
#$ sendcontrol [                                                                                                              
#$ sendcharacter :wq                                                                                                          
#$ sendcontrol m                                                                                                              

cat foo.txt
rm -f foo.txt
rm -f .foo.txt.swp
```

**Comment by dashohoxha** [comment]
> Using send, it does check that each character is displayed, causing your code to hang. This is done to make the script as robust as possible,

I don't know how  `expect` works, but I don't understand how it makes the script robust, since the character that is being sent may already be on the screen (for example when editing a file with `vim`).
Anyway, this is not important for me as long as it works.

**Comment by PierreMarchand20** [comment]
Is it ok for you if we just add delay when using sendcharacter?

**Comment by dashohoxha** [comment]
Whatever you think is better.
I have already finished recording what I had to record.

**Comment by PierreMarchand20** [comment]
In this case, I close this issue and we will see if other people request this feature.
