### ISSUE TITLE
Repo SEO

### ISSUE THREAD

**Issue by lightningorb** [PierreMarchand20/asciinema_automation#2]
Hi,

I'm creating a separate ticket for this. This is the best solution for automating asciinema, because it is Python, very easy to install, very easy to use, and reading the code is a good experience.

HN is hacker news. https://news.ycombinator.com You should consider making a "Show HN" post there. Also make some posts on reddit. I found this repo due to a link in a stackoverflow post (https://stackoverflow.com/questions/53969566/how-can-i-use-scripting-automation-to-record-asciinema-recordings), but otherwise it doesn't show at all in Google.

Some organic posts on relevant boards should do the trick. Shame this exists but so hard to find. It's really great.

**Comment by PierreMarchand20** [comment]
Thank you for the information! I was not aware of "Show HN", I will check it out. By the way, you can also consider upvote my answer on https://stackoverflow.com/questions/53969566/how-can-i-use-scripting-automation-to-record-asciinema-recordings then :D I also discovered asciiscript on this post.

But keep in mind that I just wrote this code about a month ago so it may explain why it is not very well known. That and the need for automating asciinema does not seem that widespread. I will keep this issue opened for now.

**Comment by PierreMarchand20** [comment]
I posted a "Show HN" [here](https://news.ycombinator.com/item?id=32976206)

**Comment by PierreMarchand20** [comment]
Feel free to reopen the issue if needed
