### ISSUE TITLE
PyPI version

### ISSUE THREAD

**Issue by ocervell** [PierreMarchand20/asciinema_automation#6]
I would like to use `asciinema-automation` as a dependency of one of my Python package.

Could you push the package to PyPI so we can install it like `pip3 install asciinema-automation` or add it to `requirements.txt` ?

**Comment by PierreMarchand20** [comment]
Sure, I will check how to do that.

**Comment by PierreMarchand20** [comment]
It should be done now : https://pypi.org/project/asciinema-automation/0.0.4/. Do not hesitate to reopen if there is still an issue.
